
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int LGPAR = 11;
  public static final int GE = 33;
  public static final int UMINUS = 24;
  public static final int DOUBLE_CONST = 41;
  public static final int DOUBLE = 6;
  public static final int SEMI = 13;
  public static final int INT = 4;
  public static final int MINUS = 26;
  public static final int WRITE = 15;
  public static final int NOT = 29;
  public static final int AND = 30;
  public static final int LT = 34;
  public static final int RPAR = 9;
  public static final int OR = 31;
  public static final int BOOL = 5;
  public static final int RGPAR = 12;
  public static final int COMMA = 22;
  public static final int DIV = 28;
  public static final int PLUS = 25;
  public static final int ASSIGN = 16;
  public static final int IF = 17;
  public static final int LE = 35;
  public static final int EOF = 0;
  public static final int INT_CONST = 39;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int START = 3;
  public static final int EQ = 36;
  public static final int NAME = 40;
  public static final int HEAD = 2;
  public static final int TIMES = 27;
  public static final int COLON = 10;
  public static final int ELSE = 19;
  public static final int READ = 14;
  public static final int WHILE = 20;
  public static final int THEN = 18;
  public static final int LPAR = 8;
  public static final int DEF = 7;
  public static final int FALSE = 38;
  public static final int STRING_CONST = 23;
  public static final int GT = 32;
  public static final int DO = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HEAD",
  "START",
  "INT",
  "BOOL",
  "DOUBLE",
  "DEF",
  "LPAR",
  "RPAR",
  "COLON",
  "LGPAR",
  "RGPAR",
  "SEMI",
  "READ",
  "WRITE",
  "ASSIGN",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "COMMA",
  "STRING_CONST",
  "UMINUS",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "NOT",
  "AND",
  "OR",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "TRUE",
  "FALSE",
  "INT_CONST",
  "NAME",
  "DOUBLE_CONST"
  };
}

